name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Write clasp credentials
        run: |
          echo '{
            "token": {
              "access_token": "${{ secrets.CLASP_ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.CLASP_REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive",
              "token_type": "Bearer",
              "expiry_date": 3600
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLASP_CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLASP_CLIENT_SECRET }}",
              "redirectUri": "urn:ietf:wg:oauth:2.0:oob"
            },
            "isLocalCreds": false
          }' > ~/.clasprc.json

      - name: Push to Google Apps Script
        run: clasp push
